"""
bundle_generator.py
Creates a complete compliance bundle ZIP file containing:
- CycloneDX 1.6 SBOM JSON
- PDF compliance report
- Markdown remediation report
- Auto-fix recommendations
- Session metadata
This is the complete package for a compliance auditor.
"""

import json
import zipfile
import io
from datetime import datetime, timezone
from pathlib import Path

SBOM_OUTPUT_DIR = Path('../sbom-output')


def generate_compliance_bundle(session_id: str, sbom: dict, fixes: dict, pdf_bytes: bytes) -> bytes:
    """Generate a ZIP compliance bundle."""
    buffer = io.BytesIO()

    with zipfile.ZipFile(buffer, 'w', zipfile.ZIP_DEFLATED) as zf:
        # 1. CycloneDX SBOM JSON
        zf.writestr(
            f'chainsight-{session_id}/sbom.cdx.json',
            json.dumps(sbom, indent=2)
        )

        # 2. PDF compliance report
        if pdf_bytes:
            zf.writestr(
                f'chainsight-{session_id}/compliance-report.pdf',
                pdf_bytes
            )

        # 3. Auto-fix recommendations
        if fixes and fixes.get('fixes'):
            fix_lines = [
                f"# ChainSight Auto-Fix Recommendations",
                f"# Session: {session_id}",
                f"# Generated: {datetime.now(timezone.utc).isoformat()}",
                f"",
                f"# Apply these upgrades to resolve all Bob blind spots:",
                f"",
            ]
            for fix in fixes['fixes']:
                fix_lines.append(f"pip install {fix['package']}=={fix['fixed_version']}  # fixes {', '.join(fix['vulns_fixed'])}")
            zf.writestr(
                f'chainsight-{session_id}/auto-fix.sh',
                '\n'.join(fix_lines)
            )

        # 4. Session metadata JSON
        components = sbom.get('components', [])
        vulns = sbom.get('vulnerabilities', [])
        blind = [v for v in vulns if any(
            p['name'] == 'chainsight:post-training-cutoff' and p['value'] == 'true'
            for p in v.get('properties', [])
        )]

        metadata = {
            'session_id': session_id,
            'generated': datetime.now(timezone.utc).isoformat(),
            'ai_tool': 'IBM Bob 1.0',
            'training_cutoff': '2024-11-01',
            'sbom_format': 'CycloneDX 1.6',
            'total_components': len(components),
            'total_vulnerabilities': len(vulns),
            'bob_blind_spots': len(blind),
            'compliance_posture': 'FAIL' if blind else 'WARN' if vulns else 'PASS',
            'regulations': ['US-EO-14028', 'EU-CRA-Article-13', 'EU-AI-Act-Article-11'],
            'fixes_available': len(fixes.get('fixes', [])),
            'chainsight_version': '7.0',
            'generated_by': 'ChainSight — IBM Bob Dev Day Hackathon 2026'
        }
        zf.writestr(
            f'chainsight-{session_id}/metadata.json',
            json.dumps(metadata, indent=2)
        )

        # 5. README for the auditor
        readme = f"""# ChainSight Compliance Bundle
## Session: {session_id}

This bundle contains the complete supply chain security audit for AI-generated code
produced by IBM Bob.

## Contents

- `sbom.cdx.json` — CycloneDX 1.6 Software Bill of Materials
- `compliance-report.pdf` — EU CRA Article 11 compliance report
- `auto-fix.sh` — Automated remediation script
- `metadata.json` — Session metadata and compliance status

## Compliance Status

- **Bob blind spots**: {len(blind)} CVE(s) unknown to Bob at generation time
- **Total CVEs**: {len(vulns)}
- **Components**: {len(components)}
- **Posture**: {'FAIL' if blind else 'WARN' if vulns else 'PASS'}

## Regulations Addressed

- US Executive Order 14028 (SBOM requirement)
- EU Cyber Resilience Act Article 13
- EU AI Act Article 11 (technical documentation)

## Generated By

ChainSight v7.0 — IBM Bob Dev Day Hackathon 2026
AI Tool: IBM Bob 1.0 (training cutoff: 2024-11-01)
Powered by: watsonx.ai, IBM Cloudant, watsonx Orchestrate
"""
        zf.writestr(f'chainsight-{session_id}/README.md', readme)

    return buffer.getvalue()
